---
title: "EDA"
author: "Ted Ladas - s2124289"
date: "11/07/2021"
output: html_document
---

# Libraries and Requirements

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # for tidy syntax
library(janitor) # for handling column names
library(data.table) # for fast processing of data
library (skimr) # to get a fast grasp of the dataset
library(broom)
library(tidytext)
library(patchwork)
library(corrplot)
```

# Load the data files

```{r loading}
keys <-
  as.data.table(read_csv("./data/crypto_wake_up_sample_sheet.csv")) %>% clean_names()
genes <-
  as.data.table(
    read_csv(
      "./data/H99_all_genes_promoter_500nt_4mer_counts.csv",
      skip = 10,
      col_names = FALSE
    ) %>%
      row_to_names(row_number = 1)
  ) %>% clean_names() %>% mutate_at(vars(-gene), as.numeric)
experiment <-
  as.data.table(read_csv(
    "./data/CW_kallisto_abundance_fold_change_long_by_gene.csv"
  )) %>% clean_names()
```
# Missing Data Handling

```{r help-missing}
handle.missing.data <- function(df) {
  df <- df %>% na.omit() %>% filter(fold_change != Inf)
  return(df)
}
```

```{r missing}
experiment <- experiment %>% handle.missing.data()
```

```{r load-check}
keys %>% head()
genes %>% head()
experiment %>% head()
```

# Joining Datasets

```{r joins}
exp <- experiment %>% 
  left_join(keys, by = "code") %>%
  select(gene, medium, temp, time, rep, est_counts, tpm, fold_change)
skim(exp)

df <- exp %>%
  left_join(genes, by = "gene") %>%
  mutate(row_name = paste(gene, medium, temp, time, rep, sep="-"), .before=gene) %>%
  remove_rownames %>%
  column_to_rownames("row_name") %>% as.data.table()
df %>% head()

```

# Univariate Analysis

```{r help-uni}
plot.univariate <- function(var, density, dat = exp) {
  color = "blue4"
  density = TRUE
  if (var == "est_counts") {
    density = FALSE
  }
  
  if (density) {
    gg.var <- ggplot(data = dat, aes(x = .data[[var]])) +
      geom_density(col = color,
                   fill = color,
                   alpha = 0.8) +
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank()) +
      ggtitle(var) +
      xlim(0, 10 + 90 * (var != "fold_change")) +
      theme_minimal()
  } else {
    gg.var <- ggplot(data = dat, aes(x = .data[[var]])) +
      geom_histogram(
        col = color,
        fill = color,
        alpha = 0.7,
        bins = 30
      ) +
      theme(axis.title.x = element_blank(),
            axis.title.y = element_blank()) +
      ggtitle(var) +
      xlim(0, 10 + 90 * (var != "fold_change")) +
      theme_minimal()
  }
  return(gg.var)
}
```

```{r plot-uni}
names <- c("est_counts", "tpm", "fold_change")
names <- set_names(names)
plots <- map(names, ~ plot.univariate(.x))
plots[[1]] + plots[[2]] + plots[[3]]
```


Let's take tpm as the y variable.

```{r densities}
df %>% select(gene, medium, temp, time, rep, tpm) %>%
  ggplot(aes(x = tpm, col = medium, fill = medium), show.legend = FALSE) +
  geom_density(alpha = 0.8) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle("TPM") +
  facet_grid(medium ~ .) +
  xlim(0, 100) +
  theme_minimal() +
  theme(legend.position = "none")
```


```{r time-series}
exp %>%
  filter(gene %in% c("CNAG_00121", "CNAG_06917"), rep == "A", temp != "30C") %>%
  select(-est_counts, -fold_change, -rep) %>%
  ggplot(aes(x = time, y = tpm)) +
  geom_line(aes(col = gene)) +
  geom_point(aes(col = gene)) +
  facet_wrap( ~ medium + temp)
```

```{r centering}
df.sample <- df %>% sample_n(size=1e3, replace=FALSE)

df.X <- df.sample %>% select(-est_counts, -tpm, -fold_change)
df.y <- df.sample %>% select(tpm)

df.cntr.X <- select_if(df.X, is.numeric) %>% 
  scale(center = TRUE, scale = TRUE) %>% 
  as.data.table()
df.cntr.X %>% head()

svd.results <- svd(df.cntr.X)
```

# PCA

## Variance explained by PC score

```{r var-expl}
# interpret variance explained 
svd.var.exp <- tidy(svd.results, matrix = "d")

svd.var.exp %>% ggplot(aes(x = PC, cumulative)) +
  geom_line() +
  # scale_x_continuous(breaks = seq(min(svd.var.exp$PC),max(svd.var.exp$PC),by=1)) +
  coord_cartesian(xlim = c(1, 200)) +
  labs(title = "Variance Explained by PCs") +
  theme_minimal()
```
## Column wise interpretation of PCA loadings

```{r col-expl}
# interpret loadings - working on columns
svd.loadings <- tidy(svd.results, matrix="v") %>%
                mutate(element = colnames(df.cntr.X)[column])

svd.loadings %>% filter(PC<=4) %>%
  group_by(PC) %>%
  top_n(10, abs(value)) %>%
  ungroup() %>%
  mutate(element = reorder_within(element, value, PC)) %>%
  ggplot(aes(x=element, y=value, fill=factor(PC))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~PC, scales="free") +
  scale_x_reordered() + 
  coord_flip() +
  labs(title = "First four PCs of feautures") + 
  theme_minimal()
```

## Row wise interpretation of PCA loadings

```{r row-expl}
# interpret loadings - working on rows
svd.loadings.row <- tidy(svd.results, matrix="u") %>%
                mutate(gene_names = rownames(df.X)[row])

svd.loadings.row %>% filter(PC<=4) %>%
  group_by(PC) %>%
  top_n(10, abs(value)) %>%
  ungroup() %>%
  mutate(gene_names = reorder_within(gene_names, value, PC)) %>%
  ggplot(aes(x=gene_names, y=value, fill=factor(PC))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~PC, scales="free") +
  scale_x_reordered() + 
  coord_flip() +
  labs(title = "First four PCs of feautures") + 
  theme_minimal()
```

## PCA Biplot

```{r biplot}
# final plot
svd.pcs <- tidy(svd.results, matrix = "u")

svd.pcs.1 <- svd.pcs %>% filter(PC == 1) %>%
  mutate(PC1 = value) %>%
  select(PC1)
svd.pcs.2 <- svd.pcs %>% filter(PC == 2) %>%
  mutate(PC2 = value) %>%
  select(PC2)
svd.pcs.3 <- svd.pcs %>% filter(PC == 3) %>%
  mutate(PC3 = value) %>%
  select(PC3)
df.pcs <- cbind(df.y, svd.pcs.1, svd.pcs.2, svd.pcs.3)

df.pcs %>%
  ggplot(aes(
    x = PC1,
    y = PC2,
    col = tpm,
    fill = tpm
  )) +
  geom_point(shape = 21, col = "black") +
  labs(title = "PC1 vs PC2", fill = "TPM") +
  theme_minimal()
```
# Bivariate Analysis

```{r bivar}
numcols <- sapply(df, is.numeric)
df.corr <- df[, ..numcols] %>% cor(use="pairwise.complete")

df.corr.big <- df.corr*(abs(df.corr)>0.6)
df.corr.big <- df.corr.big[-which(abs(rowSums(df.corr.big))==1),-which(abs(colSums(df.corr.big))==1)]

square.cor <- corrplot(df.corr.big,
                       order="hclust",
                       addrect=10,
                       method='square',
                       diag=FALSE,
                       tl.col="black",
                       tl.cex = 0.9,
                       outline=TRUE,
                       cl.lim=c(-1, 1),
                       mar=c(0,0,1.5,0))
```


